// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3x62e8H37c7A8QwjKESJK4EbmT_4t_U8',
    appId: '1:806271261086:web:6e706b5d5b710bac751e8f',
    messagingSenderId: '806271261086',
    projectId: 'appsafelife2',
    authDomain: 'appsafelife2.firebaseapp.com',
    storageBucket: 'appsafelife2.firebasestorage.app',
    measurementId: 'G-V5HH4PLDQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQaETeNcTmtCUjfO_UPIfMQsobOf_04Q4',
    appId: '1:806271261086:android:4726d1107c0e9c30751e8f',
    messagingSenderId: '806271261086',
    projectId: 'appsafelife2',
    storageBucket: 'appsafelife2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI9uf4QfP9q3voRUTOtmMw2-_sNww3jk4',
    appId: '1:806271261086:ios:23919bb22bb0d2bd751e8f',
    messagingSenderId: '806271261086',
    projectId: 'appsafelife2',
    storageBucket: 'appsafelife2.firebasestorage.app',
    iosClientId: '806271261086-7aab1f9ka5tfcbc8t7i0nvnlqsnp0f32.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI9uf4QfP9q3voRUTOtmMw2-_sNww3jk4',
    appId: '1:806271261086:ios:23919bb22bb0d2bd751e8f',
    messagingSenderId: '806271261086',
    projectId: 'appsafelife2',
    storageBucket: 'appsafelife2.firebasestorage.app',
    iosClientId: '806271261086-7aab1f9ka5tfcbc8t7i0nvnlqsnp0f32.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3x62e8H37c7A8QwjKESJK4EbmT_4t_U8',
    appId: '1:806271261086:web:ca7309e0afda344b751e8f',
    messagingSenderId: '806271261086',
    projectId: 'appsafelife2',
    authDomain: 'appsafelife2.firebaseapp.com',
    storageBucket: 'appsafelife2.firebasestorage.app',
    measurementId: 'G-JGQDJFE87Z',
  );
}
